name: Infra CI

on:
  push:
    branches: [main]
    paths:
      - "infra/modules/**"
      - "infra/pipeline/**"

  pull_request:
    paths:
      - "infra/modules/**"
      - "infra/pipeline/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/pipeline

    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        timeout-minutes: 5
        run: terraform plan -no-color -lock-timeout=60s

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
